Irrlicht 3D Engine: irr::video::S3DVertex2TCoords Struct Reference
irr::video::S3DVertex2TCoords Struct Reference
Vertex with two texture coordinates.
#include <S3DVertex.h>
Public Member Functions
S3DVertex2TCoords ()
default constructor
S3DVertex2TCoords (f32 x, f32 y, f32 z, SColor c, f32 tu, f32 tv, f32 tu2, f32 tv2)
constructor with two different texture coords, but no normal
S3DVertex2TCoords (const core::vector3df &pos, SColor color, const core::vector2d< f32 > &tcoords, const core::vector2d< f32 > &tcoords2)
constructor with two different texture coords, but no normal
S3DVertex2TCoords (const core::vector3df &pos, const core::vector3df &normal, const SColor &color, const core::vector2d< f32 > &tcoords, const core::vector2d< f32 > &tcoords2)
constructor with all values
S3DVertex2TCoords (f32 x, f32 y, f32 z, f32 nx, f32 ny, f32 nz, SColor c, f32 tu, f32 tv, f32 tu2, f32 tv2)
constructor with all values
S3DVertex2TCoords (f32 x, f32 y, f32 z, f32 nx, f32 ny, f32 nz, SColor c, f32 tu, f32 tv)
constructor with the same texture coords and normal
S3DVertex2TCoords (const core::vector3df &pos, const core::vector3df &normal, SColor color, const core::vector2d< f32 > &tcoords)
constructor with the same texture coords and normal
S3DVertex2TCoords (S3DVertex &o)
constructor from S3DVertex
S3DVertex2TCoords getInterpolated (const S3DVertex2TCoords &other, f32 d)
E_VERTEX_TYPE getType () const
bool operator!= (const S3DVertex2TCoords &other) const
Inequality operator.
bool operator< (const S3DVertex2TCoords &other) const
bool operator== (const S3DVertex2TCoords &other) const
Equality operator.
Public Attributes
core::vector2d< f32 > TCoords2
Second set of texture coordinates.
Detailed Description
Vertex with two texture coordinates.
Usually used for geometry with lightmaps or other special materials.
Definition at line 108 of file S3DVertex.h.
Constructor & Destructor Documentation
irr::video::S3DVertex2TCoords::S3DVertex2TCoords () [inline]
default constructor
Definition at line 111 of file S3DVertex.h.
Referenced by getInterpolated().
irr::video::S3DVertex2TCoords::S3DVertex2TCoords (f32 x, f32 y, f32 z, SColor c, f32 tu, f32 tv, f32 tu2, f32 tv2) [inline]
constructor with two different texture coords, but no normal
Definition at line 114 of file S3DVertex.h.
irr::video::S3DVertex2TCoords::S3DVertex2TCoords (const core::vector3df & pos, SColor color, const core::vector2d< f32 > & tcoords, const core::vector2d< f32 > & tcoords2) [inline]
constructor with two different texture coords, but no normal
Definition at line 118 of file S3DVertex.h.
irr::video::S3DVertex2TCoords::S3DVertex2TCoords (const core::vector3df & pos, const core::vector3df & normal, const SColor & color, const core::vector2d< f32 > & tcoords, const core::vector2d< f32 > & tcoords2) [inline]
constructor with all values
Definition at line 123 of file S3DVertex.h.
irr::video::S3DVertex2TCoords::S3DVertex2TCoords (f32 x, f32 y, f32 z, f32 nx, f32 ny, f32 nz, SColor c, f32 tu, f32 tv, f32 tu2, f32 tv2) [inline]
constructor with all values
Definition at line 128 of file S3DVertex.h.
irr::video::S3DVertex2TCoords::S3DVertex2TCoords (f32 x, f32 y, f32 z, f32 nx, f32 ny, f32 nz, SColor c, f32 tu, f32 tv) [inline]
constructor with the same texture coords and normal
Definition at line 132 of file S3DVertex.h.
irr::video::S3DVertex2TCoords::S3DVertex2TCoords (const core::vector3df & pos, const core::vector3df & normal, SColor color, const core::vector2d< f32 > & tcoords) [inline]
constructor with the same texture coords and normal
Definition at line 136 of file S3DVertex.h.
irr::video::S3DVertex2TCoords::S3DVertex2TCoords (S3DVertex & o) [inline]
constructor from S3DVertex
Definition at line 141 of file S3DVertex.h.
Member Function Documentation
S3DVertex2TCoords irr::video::S3DVertex2TCoords::getInterpolated (const S3DVertex2TCoords & other, f32 d) [inline]
Definition at line 171 of file S3DVertex.h.
References irr::core::clamp(), irr::video::S3DVertex::Color, irr::core::vector3d< T >::getInterpolated(), irr::core::vector2d< T >::getInterpolated(), irr::video::SColor::getInterpolated(), irr::video::S3DVertex::Normal, irr::video::S3DVertex::Pos, S3DVertex2TCoords(), irr::video::S3DVertex::TCoords, and TCoords2.
E_VERTEX_TYPE irr::video::S3DVertex2TCoords::getType () const [inline]
Reimplemented from irr::video::S3DVertex.
Definition at line 166 of file S3DVertex.h.
References irr::video::EVT_2TCOORDS.
bool irr::video::S3DVertex2TCoords::operator!= (const S3DVertex2TCoords & other) const [inline]
Inequality operator.
Definition at line 154 of file S3DVertex.h.
References TCoords2.
bool irr::video::S3DVertex2TCoords::operator< (const S3DVertex2TCoords & other) const [inline]
Definition at line 160 of file S3DVertex.h.
References TCoords2.
bool irr::video::S3DVertex2TCoords::operator== (const S3DVertex2TCoords & other) const [inline]
Equality operator.
Definition at line 147 of file S3DVertex.h.
References TCoords2.
Member Data Documentation
core::vector2d<f32> irr::video::S3DVertex2TCoords::TCoords2
Second set of texture coordinates.
Definition at line 144 of file S3DVertex.h.
Referenced by getInterpolated(), operator!=(), irr::scene::SVertexTCoordsScaleManipulator::operator()(), operator<(), and operator==().
The documentation for this struct was generated from the following file:
S3DVertex.h